base_global_planner: global_planner/GlobalPlanner

GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.5
  visualize_potential: false
  use_dijkstra: false
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  neutral_cost: 50
  outline_map: false