robot_radius: 0.1


map_update_rate: 2.5
transform_tolerance: 2.5


 
   
my:
   enabled: true
   sim_time: true
   
inflation_layer:
   enabled: true
   inflation_radius: 0.05
   cost_scaling_factor: 10.0
   
obstacle_layer:
   enabled: true

   obstacle_range: 4.0
   raytrace_range: 4.5
   combination_method: 1
   
   observation_sources: road obstacle
   track_unknown_space: true
   obstacle:
      data_type: LaserScan
      topic: scan_filtered
      marking: true
      clearing: true
      max_obstacle_height: 2.0
      min_obstacle_height: -2.0
      sensor_frame: hokuyo_link

      
   road:
      data_type: PointCloud2
      topic: NavPointData
      marking: true
      clearing: true
      max_obstacle_height: 2.0
      min_obstacle_height: -2.0
      sensor_frame: base_footprint
      
   
   
   
   