#TrajectoryPlannerROS:
#  max_vel_x: 0.5
#  min_vel_x: -0.1
#  max_vel_theta: 1.5
#  min_in_place_vel_theta: 0.05

#  acc_lim_theta: 1.5
#  acc_lim_x: 1.0
#  acc_lim_y: 0
  
#  xy_goal_tolerance: 0.01
#
#  controller_frequency: 8.0
#  holonomic_robot: false
#  dwa: false
#  meter_scoring: true
  
  
DWAPlannerROS:
   acc_lim_y: 0.0
   acc_lim_x: 1.0
   min_vel_x: -0.1
   max_vel_x: 1.0
   min_vel_y: 0
   max_vel_y: 0
   min_rot_vel: 0.2
   max_rot_val: 0.8
   xy_goal_tolerance: 0.2
   occdist_scale: 0.001
   path_distance_bias: 60
   publish_cost_grid: true

