global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  resolution: 0.05
  static_map: false
  origin_x: -15.0
  origin_y: -15.0
  width: 30.0
  height: 30.0