global_costmap:
   map_type: costmap
   global_frame: odom
  
   robot_base_frame: base_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   #static_map: true
   static_map: false
   rolling_window: true

   #origin_x: -12.5
   #origin_y: -12.5
   width: 9.0
   height: 9.0
   plugins:
      #
      #- {name: static,                type: "costmap_2d::StaticLayer"}
      
      
      - {name: my,                type: "simple_layer_namespace::MyLayer"}
      - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}