global_costmap:
   map_type: costmap
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: true
   
   
   
   origin_x: -7.5
   origin_y: -7.5
   width: 15.0
   height: 15.0
   
   plugins:
      #
      #- {name: static,                type: "costmap_2d::StaticLayer"}
      
      
      - {name: my,                type: "simple_layer_namespace::MyLayer"}
      - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}